name: Build and Deploy
run-name: Build and deploy docker image on dockerhub

on: [push, workflow_dispatch]
jobs:
    build_base_job:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Autenticate with Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Build n8n-oracle
            run: docker build -t n8n-oracle .
  
          - name: Push n8n-oracle
            run: |
              docker tag n8n-oracle "${{ secrets.DOCKERHUB_USERNAME }}/n8n-oracle"
              docker push "${{ secrets.DOCKERHUB_USERNAME }}/n8n-oracle"
